# Generated by Django 4.0.4 on 2022-05-03 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Выбор для вопросов',
                'verbose_name_plural': 'Выборы для вопросов',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('sex', models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], default=1, max_length=7, verbose_name='Пол пациента')),
                ('insurance', models.CharField(blank=True, max_length=100, verbose_name='Страховая организация')),
                ('policy', models.CharField(blank=True, max_length=100, verbose_name='Страховое свидетельство')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Домашний адрес')),
                ('number_phone', models.CharField(blank=True, max_length=100, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='Электронная почта')),
                ('parent_name', models.CharField(blank=True, max_length=100, verbose_name='ФИО родителя')),
                ('parent_number_phone', models.CharField(blank=True, max_length=100, verbose_name='Номер телефона родителя')),
                ('parent_email', models.EmailField(blank=True, max_length=100, verbose_name='Электронная почта родителя')),
                ('nation', models.CharField(choices=[('Русские', 'Русские'), ('Украинцы', 'Украинцы'), ('Немцы', 'Немцы'), ('Казахи', 'Казахи'), ('Белорусы', 'Белорусы'), ('Алтайцы', 'Алтайцы'), ('Кумандинцы', 'Кумандинцы'), ('Татары', 'Татары'), ('Другая', 'Другая')], default=1, max_length=10, verbose_name='Нация пациента')),
                ('mother_nation', models.CharField(choices=[('Русские', 'Русские'), ('Украинцы', 'Украинцы'), ('Немцы', 'Немцы'), ('Казахи', 'Казахи'), ('Белорусы', 'Белорусы'), ('Алтайцы', 'Алтайцы'), ('Кумандинцы', 'Кумандинцы'), ('Татары', 'Татары'), ('Другая', 'Другая')], default=1, max_length=10, verbose_name='Нация матери пациента')),
                ('father_nation', models.CharField(choices=[('Русские', 'Русские'), ('Украинцы', 'Украинцы'), ('Немцы', 'Немцы'), ('Казахи', 'Казахи'), ('Белорусы', 'Белорусы'), ('Алтайцы', 'Алтайцы'), ('Кумандинцы', 'Кумандинцы'), ('Татары', 'Татары'), ('Другая', 'Другая')], default=1, max_length=10, verbose_name='Нация отца пациента')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Дата регистрации пациента')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questname', models.CharField(max_length=100, verbose_name='Название вопроса')),
                ('fieldtest', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='amscapp.field')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientname', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='amscapp.patient')),
            ],
            options={
                'verbose_name': 'Анкетирование',
                'verbose_name_plural': 'Анкетирования',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100, verbose_name='Вариант ответа')),
                ('questchoice', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='amscapp.field')),
            ],
            options={
                'verbose_name': 'Поле для выбора',
                'verbose_name_plural': 'Поля для выборов',
            },
        ),
    ]
