# Generated by Django 4.0.4 on 2022-05-06 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amscapp', '0002_question_choiceteset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='choiceteset',
            new_name='choicetest',
        ),
    ]
