# Generated by Django 4.0.4 on 2022-05-19 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amscapp', '0004_option_rename_patientname_complaint_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fields',
            new_name='Field',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
