# Generated by Django 4.0.4 on 2022-05-19 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amscapp', '0005_rename_fields_field_delete_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AddField(
            model_name='complaint',
            name='field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='amscapp.field'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='amscapp.option'),
        ),
    ]
